name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Get dependencies and build binary
      run: make all
    - name: Test source
      run: make test FLAGS="-v -coverprofile=/tmp/cover.out"
    - name: Vet source
      run: make vet

  # The GitHub action, securego/gosec, doesn't seem to work properly when it's
  # preceded by another action that supplies the env var, GOROOT. Example error:
  #
  #   loading files from package ".": err: exit status 2: stderr: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.17.7/x64
  #
  # As a workaround, do this security scan separately.
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: --tests . ./internal/...
